executable = king_bkg_trial_generation.py

arguments = --sin_dec $(SINDEC) \
            --N_trials 1000 \
            --seed 0 \
            --mp_cpus 32 \
            --gammas 1.8 2.0 2.5 2.7 \
            --out_dir /data/user/fkrafft/csky_king_tests/$(FILE_ID) \
            --ana_dir /data/user/fkrafft/csky_gfu_tests \
            --file_identifier $(FILE_ID) \
            --calc_sens 1 \
            --ang_err_bins $(ANGERRBINS) \
            --min_counts $(MINCOUNTS) \

output = /data/user/fkrafft/csky_king_tests/$(FILE_ID)/log/job_sindec_$(SINDEC)_angerrbins_$(ANGERRBINS)_mincounts_$(MINCOUNTS).out
error  = /data/user/fkrafft/csky_king_tests/$(FILE_ID)/log/job_sindec_$(SINDEC)_angerrbins_$(ANGERRBINS)_mincounts_$(MINCOUNTS).err
log    = /scratch/fkrafft/logs/king_trial_job.log

transfer_input_files = king_bkg_trial_generation.py
when_to_transfer_output = ON_EXIT
should_transfer_files = YES

request_cpus = 32
request_memory = 8GB

queue SINDEC, ANGERRBINS, MINCOUNTS, FILE_ID from (
-0.5  5  150  min_count_150_angErr5
-0.3  5  150  min_count_150_angErr5
-0.15  5  150  min_count_150_angErr5
-0.1  5  150  min_count_150_angErr5
-0.05  5  150  min_count_150_angErr5
 0.0  5  150  min_count_150_angErr5
 0.2  5  150  min_count_150_angErr5
 0.4  5  150  min_count_150_angErr5
-0.5  5  300  min_count_300_angErr5
-0.3  5  300  min_count_300_angErr5
-0.15  5  300  min_count_300_angErr5
-0.1  5  300  min_count_300_angErr5
-0.05  5  300  min_count_300_angErr5
 0.0  5  300  min_count_300_angErr5
 0.2  5  300  min_count_300_angErr5
 0.4  5  300  min_count_300_angErr5
-0.5  5  500  min_count_500_angErr5
-0.3  5  500  min_count_500_angErr5
-0.15  5  500  min_count_500_angErr5
-0.1  5  500  min_count_500_angErr5
-0.05  5  500  min_count_500_angErr5
 0.0  5  500  min_count_500_angErr5
 0.2  5  500  min_count_500_angErr5
 0.4  5  500  min_count_500_angErr5
-0.5  5  1000  min_count_1000_angErr5
-0.3  5  1000  min_count_1000_angErr5
-0.15  5  1000  min_count_1000_angErr5
-0.1  5  1000  min_count_1000_angErr5
-0.05  5  1000  min_count_1000_angErr5
 0.0  5  1000  min_count_1000_angErr5
 0.2  5  1000  min_count_1000_angErr5
 0.4  5  1000  min_count_1000_angErr5

-0.5  15  150  min_count_150_angErr15
-0.3  15  150  min_count_150_angErr15
-0.15  15  150  min_count_150_angErr15
-0.1  15  150  min_count_150_angErr15
-0.05  15  150  min_count_150_angErr15
 0.0  15  150  min_count_150_angErr15
 0.2  15  150  min_count_150_angErr15
 0.4  15  150  min_count_150_angErr15
-0.5  15  300  min_count_300_angErr15
-0.3  15  300  min_count_300_angErr15
-0.15  15  300  min_count_300_angErr15
-0.1  15  300  min_count_300_angErr15
-0.05  15  300  min_count_300_angErr15
 0.0  15  300  min_count_300_angErr15
 0.2  15  300  min_count_300_angErr15
 0.4  15  300  min_count_300_angErr15
-0.5  15  500  min_count_500_angErr15
-0.3  15  500  min_count_500_angErr15
-0.15  15  500  min_count_500_angErr15
-0.1  15  500  min_count_500_angErr15
-0.05  15  500  min_count_500_angErr15
 0.0  15  500  min_count_500_angErr15
 0.2  15  500  min_count_500_angErr15
 0.4  15  500  min_count_500_angErr15
-0.5  15  1000  min_count_1000_angErr15
-0.3  15  1000  min_count_1000_angErr15
-0.15  15  1000  min_count_1000_angErr15
-0.1  15  1000  min_count_1000_angErr15
-0.05  15  1000  min_count_1000_angErr15
 0.0  15  1000  min_count_1000_angErr15
 0.2  15  1000  min_count_1000_angErr15
 0.4  15  1000  min_count_1000_angErr15

)
