executable = king_bkg_trial_generation.py

arguments = --sin_dec $(SINDEC) \
            --N_trials $(NTRIALS) \
            --seed 0 \
            --mp_cpus 32 \
            --gammas 1.0 1.7 2.0 2.3 2.5 2.7 3.0 3.3 4.0 \
            --out_dir /data/user/fkrafft/csky_king_tests/$(FILE_ID) \
            --ana_dir /data/user/fkrafft/csky_gfu_tests \
            --file_identifier $(FILE_ID) \
            --calc_sens 1 \
            --ang_err_bins $(ANGERRBINS) \
            --min_counts $(MINCOUNTS) \
            --signal_injection_gamma $(SIGNAL_INJ_GAMMA) \

output = /data/user/fkrafft/csky_king_tests/$(FILE_ID)/log/job_sindec_$(SINDEC)_angerrbins_$(ANGERRBINS)_mincounts_$(MINCOUNTS).out
error  = /data/user/fkrafft/csky_king_tests/$(FILE_ID)/log/job_sindec_$(SINDEC)_angerrbins_$(ANGERRBINS)_mincounts_$(MINCOUNTS).err
log    = /scratch/fkrafft/logs/king_trial_job.log

transfer_input_files = king_bkg_trial_generation.py
when_to_transfer_output = ON_EXIT
should_transfer_files = YES

request_cpus = 32
request_memory = 8GB

queue SINDEC, ANGERRBINS, MINCOUNTS, NTRIALS, SIGNAL_INJ_GAMMA, FILE_ID, from (
-0.5 12 300 1000 2.5 E5_a36baa_D9_83b58e_S12_MC300_PST_energy_bins_ext_gamma_range
-0.1 12 300 1000 2.5 E5_a36baa_D9_83b58e_S12_MC300_PST_energy_bins_ext_gamma_range
0.4 12 300 1000 2.5 E5_a36baa_D9_83b58e_S12_MC300_PST_energy_bins_ext_gamma_range
)