executable = king_bkg_trial_generation.py

arguments = --sin_dec $(SINDEC) \
            --N_trials 1000 \
            --seed $(SEED) \
            --mp_cpus 32 \
            --gammas 1.8 2.0 2.5 2.7 \
            --out_dir /data/user/fkrafft/csky_king_tests/$(FILE_ID) \
            --ana_dir /data/user/fkrafft/csky_gfu_tests \
            --file_identifier $(FILE_ID)

output = /data/user/fkrafft/csky_king_tests/$(FILE_ID)/log/job_sindec_$(SINDEC)_seed_$(SEED).out
error  = /data/user/fkrafft/csky_king_tests/$(FILE_ID)/log/job_sindec_$(SINDEC)_seed_$(SEED).err
log    = /scratch/fkrafft/logs/king_trial_job.log

transfer_input_files = king_bkg_trial_generation.py
when_to_transfer_output = ON_EXIT
should_transfer_files = YES

request_cpus = 32
request_memory = 8GB

queue SINDEC, SEED, FILE_ID from (
-0.5  0  equal_p_angErr_fixed_logE_dec
-0.3  0  equal_p_angErr_fixed_logE_dec
-0.15  0  equal_p_angErr_fixed_logE_dec
-0.1  0  equal_p_angErr_fixed_logE_dec
-0.05  0  equal_p_angErr_fixed_logE_dec
 0.0  0  equal_p_angErr_fixed_logE_dec
 0.2  0  equal_p_angErr_fixed_logE_dec
 0.4  0  equal_p_angErr_fixed_logE_dec
)
