executable = king_bkg_trial_generation.py

arguments = --sin_dec $(SINDEC) \
            --N_trials $(NTRIALS) \
            --seed 0 \
            --mp_cpus 32 \
            --gammas 1.8 2.0 2.5 2.7 \
            --out_dir /data/user/fkrafft/csky_king_tests/$(FILE_ID) \
            --ana_dir /data/user/fkrafft/csky_gfu_tests \
            --file_identifier $(FILE_ID) \
            --calc_sens 1 \
            --ang_err_bins $(ANGERRBINS) \
            --min_counts $(MINCOUNTS) \

output = /data/user/fkrafft/csky_king_tests/$(FILE_ID)/log/job_sindec_$(SINDEC)_angerrbins_$(ANGERRBINS)_mincounts_$(MINCOUNTS).out
error  = /data/user/fkrafft/csky_king_tests/$(FILE_ID)/log/job_sindec_$(SINDEC)_angerrbins_$(ANGERRBINS)_mincounts_$(MINCOUNTS).err
log    = /scratch/fkrafft/logs/king_trial_job.log

transfer_input_files = king_bkg_trial_generation.py
when_to_transfer_output = ON_EXIT
should_transfer_files = YES

request_cpus = 16
request_memory = 6GB

queue SINDEC, ANGERRBINS, MINCOUNTS, NTRIALS, FILE_ID, from (
-0.05  12  150 1000 min_count_150_angErr12_e4floor_fits
)
